[숫자 야구 step1] 손옥무 미션 제출합니다.
wowap-course/kotlin-baseball pull request #1
Opened 2024-04-08 08:14 UTC by okdoittttt

중간점검 부탁드립니다.

2024-04-08 09:04 UTC, SeongHoonC requested changes
테스트 코드는 둘째치고 MVC 를 철저히 분리해야합니다.
1. MVC 분리
2. 객체가 스스로 일할 수 있도록 설계
3. 다른 객체, 함수로 전달할 때 List 를 불변으로 만들기

2024-04-08 09:04 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    private val outputview = OutputView()
Referee 가 상태를 가지고 있을 필요가 없을 것 같네요!

2024-04-08 09:04 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    fun call(computer: MutableList<Int>, player: List<Int>) {
1. List 인데 변수명을 복수형으로 해보는게 어떨까요.

2024-04-10 17:19 UTC, g0rnn reviewed
고생하셨습니다!! 전반적으로 인상깊에 잘봤습니다! 작성하신 코드 보고 저도 배운게 몇가지 있었어요! 

다만 아쉬운건 문제 조건에 만족하지 못한 부분이 있었고 컬렉션을 좀더 활용했으면 좋을 것 같아요

2024-04-10 17:19 UTC, g0rnn commented on src/main/kotlin/baseball/GameController.kt
> +            val input = inputview.printInputNumber()
inputview가 뭔가를 print한다는게 조금 어색한거 같아요! 다른 이름을 고려해보는건 어떨까요?

2024-04-10 17:19 UTC, g0rnn commented on src/main/kotlin/baseball/GameController.kt
> +        }
while문을 사용하여 controller의 내부를 구현하면 제가 고민하고 있던 스택오버플로우 문제를 해결하면서 좀더 깔끔하게 구현할 수 있군요!

2024-04-10 17:19 UTC, g0rnn commented on src/main/kotlin/baseball/domain/computer/Computer.kt
> +    var number = mutableListOf<Int>()
컴퓨터(상대방)이 가지고 있는 숫자를 외부에서 임의로 변경하게되면 위험하지 않을가요?

2024-04-11 05:44 UTC, Redish03 reviewed
고생하셨습니다! data class로 ball, strike 정보를 따로 뺀걸 인상깊게 봤습니다

아쉬운 부분에 대해서 comment 남겨놨습니다 고생하셨습니당

2024-04-11 05:44 UTC, Redish03 commented on src/main/kotlin/baseball/GameController.kt
> +    private val gameSetup = ThreeRandomNumberGenerator()
gameSetup 보단 다른 이름을 사용해보는건 어떤가요? 예를 들면 answer라던가, target 등등..

2024-04-11 05:44 UTC, Redish03 commented on src/main/kotlin/baseball/domain/numberRules/SelectNumber.kt
> +        }
indent 2 확인해주세요!

2024-04-11 05:44 UTC, Redish03 commented on src/test/kotlin/study/BaseballTest.kt
> +        input.add(9)
`val input = mutableListOf<Int>(7, 8, 9)`

이런식으로도 할 수 있습니다..!

2024-04-11 05:44 UTC, Redish03 commented on src/test/kotlin/study/BaseballTest.kt
> +    }
model 에 대해서 테스트 하는게 아닌것 같아요!

2024-04-11 16:35 UTC, SeongHoonC requested changes
이전에 비해서 나아졌지만 전체적으로 가변, 읽기 전용의 차이를 이해하고 적용할 필요성이 보입니다. 

또한 interface 의 역할이란 개념을 오용하는 것으로 보여요. 무조건 추상화한다고 좋은건 아닙니다.

리뷰 반영하고 재요청해주세요! :)

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +            }
depth 가 2 입니다

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    fun call(computerNumbers: MutableList<Int>, playerNumbers: List<Int>): Pair<Int, Int> {
Pair 가 아닌 이미 만들어 놓은 객체를 써보는건 어떤가요?

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    fun call(computerNumbers: MutableList<Int>, playerNumbers: List<Int>): Pair<Int, Int> {
가변 리스트를 인자로 받으면 리스트 내부 변경이 일어날 수도 있겠네요.
어떤 문제로 이어질까요?

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Computer.kt
> +}
이 객체의 책임은 무엇인가요?

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/SelectNumber.kt
> +class SelectNumber : PlayerSelectNumberRule {
변수, 객체 -> 명사형
함수 -> 동사

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/SelectNumber.kt
> +        }
문자를 숫자 리스트으로 바꿔주는 역할로 보이는데 InputView 의 역할로 볼 수 있지 않을까요?
또한 숫자가 아닌 것을 입력해도 문제 없이 다음 단계로 넘어갑니다ㅜ

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/ThreeRandomNumberGenerator.kt
> +        println(computer.number)
필요없는 print 로 보이네요

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/ThreeRandomNumberGenerator.kt
> +        }
Computer 객체를 생성하고 숫자를 넣다가 다시 number 를 빼서 반환하네요,,?

2024-04-11 16:35 UTC, SeongHoonC commented on src/test/kotlin/study/BaseballTest.kt
> +        val player = mutableListOf(4, 5, 6)
MutableList 와 List 의 차이가 무엇인가요?

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/ComputerGenerateNumberRule.kt
> +}
여기도 MutableList 네요.

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    private var score = Score(RESET_NUMBER, RESET_NUMBER)
var, val 의 차이가 무엇인가요?

2024-04-11 16:35 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Score.kt
> +)
data class 와 class 의 차이는 무엇인가요?

2024-04-12 16:37 UTC, okdoittttt commented on src/main/kotlin/baseball/domain/computer/Computer.kt
> +}
처음에 숫자를 입력받아서 비교할 대상 객체를 생성하는게 좋을 것 같아서 그렇게 했습니다.

지금 생각해보니 어차피 랜덤한 숫자 3개를 갖고 있기만하면 되니 딱히 필요 없다고 생각되네요.

2024-04-12 16:51 UTC, okdoittttt commented on src/test/kotlin/study/BaseballTest.kt
> +        val player = mutableListOf(4, 5, 6)
MutableList은 리스트 안에 요소를 추가하거나 삭제하는 것이 가능한 자료구조이고, List는 요소를 추가 삭제하는 것이 불가능합니다.

테스트코드는 List로 값을 초기화하도록 수정했습니다.

2024-04-12 16:54 UTC, okdoittttt commented on src/main/kotlin/baseball/domain/computer/Referee.kt
> +    private var score = Score(RESET_NUMBER, RESET_NUMBER)
val은 불변변수이고, var은 가변변수입니다. 변수 값이 변경되어야 할 때 var 변수를 사용할 수 있습니다.

score 변수가 값이 변해야하니 var로 해야한다고 착각했네요. 감사합니다.

2024-04-12 16:59 UTC, okdoittttt commented on src/main/kotlin/baseball/domain/Score.kt
> +)
data class는 데이터를 전달하거나 저장하는데 사용되는 클래스입니다.

제가 작성한 코드에서 스트라이크와 볼 변수가 View 코드에서 도메인을 참조해야 하도록 작성되어  있어서 따로 분리해보았습니다.
하지만 Referee 클래스에서 따로 반환받아 View에게 전달하는 식으로 코드를 추가로 수정했기 때문에 필요없어 보이네요.

2024-05-01 05:38 UTC, SeongHoonC requested changes
리뷰 반영 부탁드리겠습니다!

2024-05-01 05:38 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Score.kt
> +)
차이점에 대한 공부가 더 필요한 것 같네요~

2024-05-01 05:38 UTC, SeongHoonC commented on src/test/kotlin/study/BaseballTest.kt
> +        assertThat(2).isEqualTo(ball)
assertThat(actual).isEqualTo(expected) 입니다.
순서가 반대에요..!

2024-05-01 05:38 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/computer/Computer.kt
Computer 라는 객체가 필요할까요?
필요하다면 어떤 책임을 가지고 있나요?

2024-05-01 05:38 UTC, SeongHoonC commented on src/main/kotlin/baseball/GameController.kt
> +        outputview.printWin()
게임을 재시작하는 부분이 없어요! 요구사항을 확인해주세요~

2024-05-01 05:43 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/UserInputNumbers.kt
> +        return inputNumber
사용자에게 입력을 받는다는 것은 도메인일까요?

2024-05-01 05:43 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numberRules/ComputerGenerateNumberRule.kt
> +    fun generateRandomNumber(): List<Int>
랜덤인지 모르게 추상화시켰는데 랜덤이 이름에 들어가있네요..ㅜㅜ

2024-05-15 10:59 UTC, merged