[숫자 야구 step1] 홍성우 미션 제출합니다.
wowap-course/kotlin-baseball pull request #3
Opened 2024-04-08 14:37 UTC by Redish03

# kotlin-baseball
## 구현 기능
### 1.입력
**기능**
- 사용자에게 숫자 야구 게임 숫자를 입력받음
- 게임을 새로 시작할지, 종료할지 물어봄

**예외 처리**
- 입력받은 숫자가 정수형이 아닐 경우 다시 입력
- 입력받은 숫자가 3가지가 아닐 경우 다시 입력
- 입력받은 숫자가 중복 될 경우 다시 입력
- 게임을 새로 시작할 지 물어봤을 때 1 또는 2가 아니면 다시 입력

### 2.Baseball
- 숫자 야구를 진행함
  - 같은 수가 같은 자리에 있으면 스트라이크
  - 다른 자리에 있으면 볼
  - 같은 수가 전혀 없으면 낫싱
- 컴퓨터는 random 하게 3개의 숫자를 뽑아 정답을 구성
- 만약 컴퓨터가 생각한 숫자와 사용자가 입력한 정답이 일치하면 게임 종료

---
### 개선 할 점
- interface 미구현
- Controller 로직 분리
- 함수명, 변수명 이름 미흡한 부분 많음,,,

2024-04-08 16:07 UTC, SeongHoonC requested changes
고생많았어요! 전반적으로 깔끔하지만 더 좋은 방향이 많이 보여서 코멘트 남겨봤습니다.
리뷰 반영 후 재요청해주세요~

- 커밋을 보고 어떤 요구사항을 만족하기 위함인지 알기 어려워요.
어떤 클래스 구현, 어떤 함수 구현 이라는 커밋 메세지는 직접 구현한 본인만 알 수 있겠죠?
전혀 모르는 사람이 봐도 어떤 기능을 구현하기 위해 작업한 커밋 내역이구나 알 수 있게 남겨보세요!

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/BaseballController.kt
Controller 의 위치가 여기가 맞을까요?

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/view/InputView.kt
> +    }
여기서 숫자를 입력해 달라는 의미가 단순히 Int, 숫자를 의미하는 걸까요?
InputView 에게 책임을 더 주어도 될 것 같네요

2024-04-08 16:07 UTC, SeongHoonC commented on src/test/kotlin/baseball/InputCheckerTest.kt
> +        assertThat(InputChecker().isWrongNumberInput(input)).isTrue()
assertTrue 도 있습니다 :)

2024-04-08 16:07 UTC, SeongHoonC commented on src/test/kotlin/baseball/JudgeTest.kt
> +    }
테스트에 given when then 주석을 사용하면 더 확실할 것 같아용

2024-04-08 16:07 UTC, SeongHoonC commented on src/test/kotlin/baseball/JudgeTest.kt
> +    fun `calculateBall 볼 개수를 세어준다`() {
함수 이름은 테스트 명에 넣지 않는게 좋아요. 기능 요구사항에 맞는 테스트가 어떤가요?
"두 숫자를 비교했을 떄, 값은 같고 자리만 다른 숫자가 하나라면 볼의 개수는 1 이다."
라던지 말이죠.

이렇게 하는 이유는 여러가지가 있습니다.
- 함수, 변수명이 바꼈을 때 테스트 코드 이름도 바껴야하는가?
- 프로덕트 코드의 내부 구현을 모르는 상태에서 테스트 코드만 보더라도 기능이 정상 동작함을 알 수 있어야한다.
- 등등

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateStrike(inputNum: List<Int>, answer: List<Int>): Int {
심판이 input 인지 알아야할까요..?

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateBall(inputNum: List<Int>, answer: List<Int>): Int {
List 변수명은 복수형으로 써주세요.

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateBall(inputNum: List<Int>, answer: List<Int>): Int {
함수가 인자를 받았을 때 단번에 중복이 없음을 알게 하려면 어떻게 해야할까요?

2024-04-08 16:07 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/BaseballController.kt
> +        }
depth 가 2 입니다.

2024-04-10 05:55 UTC, Redish03 commented on src/main/kotlin/baseball/domain/BaseballController.kt
MVC 패턴에 대한 지식이 아직 부족해서 실수 한 것 같습니다 허허..^_^ 감사합니다

2024-04-10 08:05 UTC, Redish03 commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateBall(inputNum: List<Int>, answer: List<Int>): Int {
> 함수가 인자를 받았을 때 단번에 중복이 없음을 알게 하려면 어떻게 해야할까요?

제가 질문을 똑바로 이해한건지 모르겠네요...! 낫싱의 경우를 말씀하시는건가요?

2024-04-10 13:50 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateBall(inputNum: List<Int>, answer: List<Int>): Int {
아닙니당! 현재는 인자로 받은 리스트 내 아이템들이 중복 가능한 상태입니다.

listOf(1,1,2) 같은게 들어올 수 있죵

그렇지 않으려면 어떻게 할 것이냐가 요점입니다!

2024-04-10 15:40 UTC, Redish03 commented on src/main/kotlin/baseball/domain/Judge.kt
> +    fun calculateBall(inputNum: List<Int>, answer: List<Int>): Int {
아 감사합니다..!

2024-04-11 13:50 UTC, g0rnn reviewed
정말 고생하셨습니다! 성우님 코드를 보니 null값을 없애기 위한 노력이라던지 여러 케이스가 있는 경우엔 when을 사용한다던지 제가 참고해야할 부분을 배울 수 있었습니다! 👍

2024-04-11 13:50 UTC, g0rnn commented on src/main/kotlin/baseball/BaseballController.kt
> +    }
when을 이용하면 좀더 직관적으로 표현할 수 있군요! 참고하겠습니다 :)

2024-04-11 13:50 UTC, g0rnn commented on src/main/kotlin/baseball/BaseballController.kt
> +        return command!!.toInt()
입력받은 값을 바로바로 확인하면 잘못된 값이 입력되는 것을 방지할 수 있군요!!

2024-04-12 17:14 UTC, okdoittttt reviewed
고생하셨어요. 코드 잘봤습니다.

2024-04-12 17:14 UTC, okdoittttt commented on src/main/kotlin/baseball/domain/InputChecker.kt
> +            require(convertedInput.toSet().size == convertedInput.size) { "[ERROR] 중복된 숫자 입력" }
require()를 사용해서 Depth 조건을 만족할 수 있네요. 참고하겠습니다.

2024-04-12 17:14 UTC, okdoittttt commented on src/main/kotlin/baseball/BaseballController.kt
> +        }
when 절에서 함수로 전달할 수도 있네요. 참고하겠습니다.

2024-04-12 17:14 UTC, okdoittttt commented on src/main/kotlin/baseball/BaseballController.kt
> +    }
run()과 startBaseball()을 따로 분리한 이유가 뭔가요?

2024-04-12 17:14 UTC, okdoittttt commented on src/main/kotlin/baseball/view/InputView.kt
> +    }
이렇게하면 변수 생성을 최소화 할 수 있어 좋아보이네요. 참고하겠습니다.

2024-04-14 07:28 UTC, Redish03 commented on src/main/kotlin/baseball/BaseballController.kt
> +    }
원래 구상했던 로직은 `decideMoreOrStop` 함수에서 사용자가 다시 한번 게임을 하고 싶을 시 `startBaseball()`을 `decideMoreOrStop`함수에서 호출하도록 하는 거였습니다! 지금 로직도 그런 상태이구요

전반적인 사이클을 한 번 돌리기 위해서입니다

2024-05-15 10:59 UTC, merged