[숫자 야구 step1] 이진우 미션 제출합니다.
wowap-course/kotlin-baseball pull request #4
Opened 2024-04-08 14:39 UTC by Jinu219

Test 작성 전 PR

2024-04-11 03:36 UTC, SeongHoonC requested changes
스스로 학습하는 방법을 조금씩 찾아가는 것 같네요.

리뷰 남겼습니다 반영하고 이해가 안가는 코멘트는 코멘트 링크와 함께 질문에 올려주세요~

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/GameController.kt
> +) {
생성자로 주입받은 이유가있나요?

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Count.kt
> +)
Count 라는 이름이 너무 범용적이네요. 어떤 Count 일까요..?

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Count.kt
> +)
data class 와 class 의 차이는 무엇인가요? :)

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Game.kt
> +        val numList = baseballNumber.toString().map { it.toInt() - '0'.toInt() }
변수명에 컬렉션이 드러나지 않도록 해주세요~

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/NumberGenerator.kt
> +    fun getNumber(): MutableList<Int>
1. 리스트는 복수형 변수를 사용
2. MutableList 말고 더 좋은게 있을 것 같네요~

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +        return randomNumber
요구사항은 1 부터 9 까지 숫자입니다.
또한 숫자가 중복 가능하네요

2024-04-11 03:36 UTC, SeongHoonC commented on src/test/kotlin/domain/GameTest.kt
GameTest 는 Game 을 테스트해야합니다. 다시 작성해주세요

2024-04-11 03:36 UTC, SeongHoonC commented on src/test/kotlin/domain/JudgementTest.kt
> +    fun `스트라이크, 볼, 나싱의 힌트를 표시한다`(){
기능 요구사항에 맞는 테스트명은 어떤가요?
"두 숫자를 비교했을 때, 값은 같고 자리만 다른 숫자가 하나라면 볼의 개수는 1 이다."
라던지 말이죠.

프로덕션 코드의 내부 구현을 모르는 상태에서 테스트 코드만 보더라도 기능이 정상 동작함을 알 수 있어야합니다.

2024-04-11 03:36 UTC, SeongHoonC commented on src/test/kotlin/domain/GameTest.kt
테스트에 로직이 없어야합니다.

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/view/OutputView.kt
> +        }
뷰가 컨트롤러를 사용하나요? 순환참조가 발생합니다.
Controller -> View -> Controller -> View -> ....

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/view/OutputView.kt
> +        }
"게임에서 승리했다", "Strike 가 3개이다" 가 View 로직일까요?

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Judgement.kt
Kotlin 스럽게 짜면 코드가 훨씬 짧아질 것 같네요..!

2024-04-11 03:36 UTC, SeongHoonC commented on src/main/kotlin/baseball/GameController.kt
> +            require(baseballNumber in GameController.MIN_BASEBALL_NUMBER..GameController.MAX_BASEBALL_NUMBER)
InputView 의 책임으로 봐도 될 것 같네요~

2024-04-11 04:22 UTC, g0rnn reviewed
게임을 구현하는게 저와 다른 접근이라 코드 읽는게 재밌었어요! 

도메인끼리 서로 알아도 되는지 고민했었는데 다시 생각해보니 도메인이 많아지면 컨트롤러의 역할이 너무 막중해지는 것 같아요..! 컨트롤러를 역할별로 분리해도 되는지 좀더 알아보고 말씀드리겠습니다!

2024-04-11 04:22 UTC, g0rnn commented on src/main/kotlin/baseball/view/OutputView.kt
> +            GameController(InputView(), OutputView()).gameRestart()
View가 Controller를 알아도 괜찮을까요?

2024-04-11 04:22 UTC, g0rnn commented on src/main/kotlin/baseball/domain/Game.kt
> +}
게임을 시작하는데 왜 심판이 뭔가를 판단하고 있죠..?

2024-04-11 04:22 UTC, g0rnn commented on src/main/kotlin/baseball/domain/Game.kt
> +        val count = Judgement().correctCount(randomBaseballNumber,numList)
도메인끼리 서로 알아도 되나용?

2024-04-11 04:22 UTC, g0rnn commented on src/main/kotlin/baseball/domain/Judgement.kt
> +class Judgement() {
Judgement가 무슨 일을 하는지 잘 짜져서 좋은것 같아요!

2024-04-11 04:22 UTC, g0rnn commented on src/main/kotlin/baseball/GameController.kt
> +        val randomBaseballNumber: List<Int> = randomNumberGenerator.getNumber()
저는 String으로 숫자를 만들었는데 List로 만들어서 구현해도 논리적으로 잘 판단할 수 있었네요!

2024-04-11 06:10 UTC, Redish03 commented on src/main/kotlin/baseball/domain/Game.kt
> +        val numList = baseballNumber.toString().map { it.toInt() - '0'.toInt() }
이해 잘 못할까봐 덧붙이는데, 
List 형이면 numList, Set 형이면 numberSet 등등
변수 이름에 List, Set, Array 등등 이런 이름들을 포함하지 말라는 뜻입니다!

2024-04-11 06:18 UTC, Redish03 commented on src/main/kotlin/baseball/GameController.kt
> +            require(baseballNumber in GameController.MIN_BASEBALL_NUMBER..GameController.MAX_BASEBALL_NUMBER)
오 입력 확인을 inputView에 넣는 것도 방법이군요! 감사합니다 :)

2024-04-11 06:44 UTC, Redish03 reviewed
앞에 리뷰 다신 분들이 많이 주셔서 저는 세세한 부분들 조정해드렸습니다~! 미션 요구사항 꼼꼼히 보세요,,ㅎ ^_^

2024-04-11 06:44 UTC, Redish03 commented on src/main/kotlin/baseball/GameController.kt
> +            require(baseballNumber in GameController.MIN_BASEBALL_NUMBER..GameController.MAX_BASEBALL_NUMBER)
수 자체를 100부터 999까지 한정 지으셨네요! 특이한 방법이라 생각합니다 .. 신기

2024-04-11 06:44 UTC, Redish03 commented on src/test/kotlin/domain/GameTest.kt
> +        if (input.toString().length != 3) {
이 부분도 상수화 할 수 있지 않을까요?

2024-04-11 06:44 UTC, Redish03 commented on src/main/kotlin/baseball/view/OutputView.kt
> +        println("S : ${strikeCount}, B : ${ballCount}")
불필요한 출력 같아보이네요!

2024-04-11 09:51 UTC, g0rnn commented on src/main/kotlin/baseball/domain/Game.kt
> +        val numList = baseballNumber.toString().map { it.toInt() - '0'.toInt() }
참고하겠씁니다!

2024-04-12 09:08 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +        return randomNumber
한 줄이면 충분해 보입니다!
```suggestion
    override fun getNumber(): List<Int> =(MIN_RANDOM_NUMBER..MAX_RANDOM_NUMBER).shuffled().take(MAX_GAME_SIZE)

```

2024-04-12 12:42 UTC, g0rnn commented on src/main/kotlin/baseball/domain/Game.kt
> +        val count = Judgement().correctCount(randomBaseballNumber,numList)
이래저래 찾아보니 로직을 구현하기 위해서는 알아도 되는 것 같습니다! 다만 (저처럼) 상호의존하고 있는 것을 주의해야할 것 같습니당

2024-04-12 13:53 UTC, Jinu219 reviewed
[숫자 야구 step1] 이진우 리뷰 반영 제출합니다.

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +        return randomNumber
0..9까지 take해서 고르는거면 중복이 안생기는거 아닌가요..?

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/GameController.kt
> +            require(baseballNumber in GameController.MIN_BASEBALL_NUMBER..GameController.MAX_BASEBALL_NUMBER)
require로 어차피 처음에는 정수인지 아닌지 필터링 되서 나오니까 
그다음에 2자리수인지 4자리수인지 비교하려고 저런 방법을 썻습니다 :3 
다른 방법이 있으면 언제든지 보겠슴다!

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/Count.kt
> +)
<img width="1031" alt="image" src="https://github.com/wowap-course/kotlin-baseball/assets/66197586/cfd36c85-9f08-4f34-8d39-69f9c4cf94fd">

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/Count.kt
> +)
Count라는 클래스명 대신에 Referee라는 클래스명이 더 무슨 역할을 하는지 명확한거 같네요! :3

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/Game.kt
> +        val numList = baseballNumber.toString().map { it.toInt() - '0'.toInt() }
:3

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/view/OutputView.kt
> +            GameController(InputView(), OutputView()).gameRestart()
View와 Controller는 서로 상호작용 할수 있는거 아닌가요?
Controller가 View를 알수있는거고 그 반대는 아닌가요?

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/view/OutputView.kt
> +        println("S : ${strikeCount}, B : ${ballCount}")
Strike카운트랑 Ball카운트는 출력해야 할거 같아서 작성하였습니다 :3 
출력 요구사항에 " 1볼 1스트라이크 " 라고 출력되는거 보다 S : 1, B : 1으로 출력되는게 이뻐 보여서.. ㅜ

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/Game.kt
> +        val count = Judgement().correctCount(randomBaseballNumber,numList)
헉 도메인 안에 있는 함수들끼리는 서로 알아도 되는거 아니였나요,,?

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/GameController.kt
> +) {
GameController가 inputView와 OutputView를 인스턴스를 통해서 사용하기 위해서 생성자로 주입을 받아야 사용가능하다고 생각했기 때문입니다!

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +        return randomNumber
수정했습니당 :3

2024-04-12 13:53 UTC, Jinu219 commented on src/main/kotlin/baseball/domain/Game.kt
> +}
게임을 시작하는것은 컨트롤러가 해야하는 책임이고 게임 내에서 게임을 진행하는건 도메인에서 게임이할 역할이라고 생각해 
인자로 randomBaseBallNumber이랑 InputBaseBallNumber를 받아서 심판이 판단하는 몫까지 있다고 생각했습니다! :3

2024-04-12 14:11 UTC, g0rnn commented on src/main/kotlin/baseball/view/OutputView.kt
> +            GameController(InputView(), OutputView()).gameRestart()
view는 모델에만 의존해야한다고 알고 있었습니다! 저는 outputView를 출력만하는 것! 이라고 이해해서 말씀드렸던 것 같아요

https://velog.io/@sebellko/MVC-%ED%8C%A8%ED%84%B4-2 여기를 참고하시면 조금 쉬운말로 정리되어 있어서 이해하기 편했습니다! 

전반적으로 제 리뷰를 다시 보니,  저도 공부하면서 코드를 짜서 제 코드도 이상한데 리뷰를 너무 다 아는 것처럼 달았네요.. 다음부터는 조금더 조심하겠습니다..!

2024-05-01 05:05 UTC, SeongHoonC requested changes
기존 리뷰들이 반영되지 않았습니다. 반영해주세요.

2024-05-01 05:05 UTC, SeongHoonC commented on src/main/kotlin/baseball/GameController.kt
> +) {
클래스 내부에서 프로퍼티로 생성하는 것과 어떤 차이가 있나요?

2024-05-08 06:28 UTC, g0rnn commented on src/main/kotlin/baseball/GameController.kt
> +        }
while문 내부에서 break조건이 없는데 어떻게 조건이 항상 true인 반복문을 끝내는지 알려주실 수 있나요? outputView에 gameEnd가 0을 반환하던데 그거랑 관련있나요?!

2024-05-15 10:58 UTC, merged