[숫자 야구 step1] 김균호 미션 제출합니다.
wowap-course/kotlin-baseball pull request #5
Opened 2024-04-08 18:17 UTC by g0rnn

depth조절에 실패했습니다.. forEach는 어떻게 빼야할지 도저히 모르겠어요..
GameController에서 run함수와 restartOrQuit함수에서 서로 호출을 시도하고 있는데 재귀적인 오류로 stakoverflow가 발생할 수 있지 않나요? (가능성은 미미하겠지만)

2024-04-10 15:39 UTC, Redish03 reviewed
고생하셨습니다! Opponent, Referee 등등 로직 분리한거 인상적으로 봤습니다. 

사용자에게 input 받은 게 잘못된 입력일 경우에 대해서 `IllegalArgumentException`을 발생시키고 `[ERROR]메세지`를 출력하는 코드가 보이지 않네요...! 기능 추가해주시면 될 것 같습니다 :)

2024-04-10 15:39 UTC, Redish03 commented on src/main/kotlin/baseball/domain/GameController.kt
> +    }
저도 이 부분 궁금했습니다..ㅎㅎ 처음에 구현할 때는 균호님이랑 똑같이 구현을 했었는데, 저도 스택오버플로우 생각해서 요구사항을 충족시키지 못한 코드를 짜긴 했었습니다...

혹시 찾아보신 자료나 그런게 있다면 같이 공유해주시면 감사할 것 같습니다!

2024-04-10 15:39 UTC, Redish03 commented on src/main/kotlin/baseball/domain/DigitsRule.kt
> +}
DigitsRule 은 제 개인적인 생각으로는 클래스로 따로 빼지 않고 함수로 둬도 되지 않을까요..!

2024-04-10 15:39 UTC, Redish03 commented on src/test/kotlin/baseball/domain/numbergenerator/RandomNumberGeneratorTest.kt
> +    }
Interface 사용해서 잘 구현 하신 것 같습니다..! 저에게도 좋은 참고가 된 것 같습니다 👍

2024-04-10 15:39 UTC, Redish03 commented on src/main/kotlin/baseball/domain/Referee.kt
> +class Referee(
Referee가 심판이라는 뜻으로 알고 있는데 균호님이 의도하신대로 아래 함수들이 심판의 역할을 나타내는지 궁금합니다..!

2024-04-11 16:09 UTC, SeongHoonC requested changes
전체적으로 책임 및 관심사 분리를 다시 설계해볼 필요가 있어보여요. 억지로 분리하고 과하게 추상화한 경향이 있습니다. 

생각해볼만한 질문도 몇가지 남겼습니다!
리뷰 반영하고 재요청해주세요! :)

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/GameController.kt
> +        else if(startOrQuit == 2) return
else if 로 체크하지만 사실 1이 아니면 어떤 것이 들어와도 게임이 끝나버리네요ㅜ

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Referee.kt
> +    fun refereeNumber(opponent : Opponent, answer : String) : String {
answer 가 숫자가 아닐 수 있겠네요:)

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Referee.kt
> +        return result.trim()
도메인에서 출력을 관여하고 있군요. 출력의 책임은 View 에게 주는게 어떤가요?

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/NumberGenerator.kt
> +    fun get() : String
1. NumberGenerator 인데 String 이면 Number 를 만들지 않을 수 있습니다.
2. get 함수가 어떤 것을 반환하는 함수인지 모르겠어요.

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +        }
중복 제거를 위해 Set 을 사용했군요! :)

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Opponent.kt
> +}
이 객체는 어떤 책임이 있나요?

2024-04-11 16:09 UTC, SeongHoonC commented on src/test/kotlin/baseball/domain/digitsrule/DigitsRuleTest.kt
> +    }
테스트만 봐도 어떤 테스트인지 알 수 있어야 합니다.

2024-04-11 16:09 UTC, SeongHoonC commented on src/test/kotlin/baseball/domain/numbergenerator/RandomNumberGeneratorTest.kt
RandomNumberGeneratorTest 인데 RandomNumberGenerator 의 기능을 테스트 하는 것은 없네요.

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Opponent.kt
> +class Opponent(referee: Referee) {
현재 Opponent 가 Referee 를 알고 Referee 가 Opponent 를 알고있는 순환참조가 일어나고 있습니다.. 어떻게 해결할 수 있을까요?

2024-04-11 16:09 UTC, SeongHoonC commented on src/test/kotlin/baseball/domain/referee/RefereeTest.kt
> +    }
테스트에는 로직이 최대한 없어야 합니다.

ValueSource 가 아닌 다른 것을 활용해 볼 수도 있겠네요
https://www.baeldung.com/parameterized-tests-junit-5

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/numbergenerator/RandomNumberGenerator.kt
> +class RandomNumberGenerator : NumberGenerator  {
DigitRule 을 따로 만들지 않고 NumberGenerator 의 책임으로 만들어도 괜찮겠네요.

2024-04-11 16:09 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/DigitsRule.kt
> +}
과한 분리라고 생각이 들기도 하네요. 전혀 set 하지 않는 setDigits 라는 이름은 확실히 바꿔야겠군요.

2024-04-11 17:36 UTC, alstjr7437 commented
고생하셨습니다!!
처음에 outputView가 많이 적은 부분에서 엄청 놀랐네요!!

그리고 짧은 이유인 Referee에서도 다시 놀랐습니다!!! ㅋㅋㅋㅋㅋ

2024-04-13 07:39 UTC, g0rnn commented
전체적인 설계부터 다시 진행하였습니다! 그러다 보니 과분리된 클래스가 눈에 더 띄더군요..! 그래서 다 지웠씁니다 :)
이외에도 함수의 이름만 보고 뭘하는지 제대로 판단하기 어려운 것들도 이름을 수정하였습니다

2024-05-01 05:26 UTC, SeongHoonC requested changes
많이 깔끔해졌네요! 리뷰 조금 달았습니다 화이팅!

2024-05-01 05:26 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/Validation.kt
> +        require(inputNumber.toSet().size == inputNumber.length) {"[ERROR]: 중복된 숫자가 있습니다."}
is 는 return 값이 boolean 일 것으로 예상됩니다.
https://soojin.ro/blog/naming-boolean-variables

requireNumber
requireThreeDigits
requireNoDuplication

같은 네이밍은 어떤가요?

2024-05-01 05:26 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/GameController.kt
> +        }.getOrNull()
valid 한 Input 을 받는건 InputView 의 책임이 아닐까요?

2024-05-01 05:26 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/GameController.kt
> +        }
Depth 를 줄일 수 있겠네요!

2024-05-01 05:26 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/ValidInput.kt
ValidInput 이 domain 에 있네요..?

2024-05-03 01:26 UTC, g0rnn commented on src/main/kotlin/baseball/domain/ValidInput.kt
사용자와 직접적인 상호작용이 없고 controller는 아니니 domain에 넣어야하는거 아닌가요?
아니면 inputview내부에서 만들어서 사용하라는건가요?

2024-05-03 09:30 UTC, SeongHoonC commented on src/main/kotlin/baseball/domain/ValidInput.kt
입력을 받는다는 것 자체가 도메인의 관심사일까요?

2024-05-15 10:58 UTC, merged